DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
EMAIL_ADDRESS VARCHAR(255) NOT NULL,
PRIMARY KEY (EMPLOYEE_ID)
);

CREATE TABLE NOTE (
NOTE_ID INT NOT NULL AUTO_INCREMENT,
EMPLOYEE_ID INT NOT NULL,
TEXT VARCHAR(255) DEFAULT NULL,
PRIMARY KEY (NOTE_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Dennis', 'Kalaygian', 'dennis@gmail.com');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Jeremy', 'Gencavage', 'jeremy@gmail.com');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Lynn', 'Johnson', 'lynn@gmail.com');
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('K', 'T', 'KT.gmail.com');

INSERT INTO NOTE (EMPLOYEE_ID, TEXT) VALUES (1, 'I eat trash on the beach for fun.');
INSERT INTO NOTE (EMPLOYEE_ID, TEXT) VALUES (2, 'I am lost in space.');
INSERT INTO NOTE (EMPLOYEE_ID, TEXT) VALUES (3, 'I am in route.');
INSERT INTO NOTE (EMPLOYEE_ID, TEXT) VALUES (4, 'You are lost in space.');
